import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";
import DesktopNav from "@/components/nav/DesktopNav";
import Sidebar from "@/components/events/Sidebar";
import GlobalClickHandler from "@/components/events/GlobalClickHandler";

const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
  variable: "--font-dm-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmMono.variable} antialiased`}>
        <GlobalClickHandler />
        <DesktopNav />
        {children}
        <Sidebar />
      </body>
    </html>
  );
}
